### PR TITLE
screw_your_friends.py

### PR DESCRIPTION
**Pull request by Princekumaraj**
funny prank code using python

### CODE REVIEW

**Comment by Princekumaraj** [comment]
Merge my request

**Comment by hanshulll** [comment]
@Princekumaraj 
**Don't worry it will be approved soon as you may know their are a lot PR's right now and also it's a one month program so don't worry it will be approved as soon as possible also I can't merge all PR's blindly as it may result in the repo being excluded from the program like many other repo so be patient full you PR will be accepted soon. Happy Hactoberfest**

**Comment by Princekumaraj** [comment]
bro it shows ur project is excluded from hacktoberfest2021. why ?

**Comment by hanshulll** [comment]
@Princekumaraj 
**Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be helped but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**

**Comment by Princekumaraj** [comment]
add labels of hacktoberfest and hacktoberfest2021 and hacktoberfest-accepted

**Comment by Princekumaraj** [comment]
now u can merge my file dude

**Pull request merged**
