### PR TITLE
Left View of Binary tree added

### PR DESCRIPTION
**Pull request by Yashika27**

### CODE REVIEW

**Review by hanshulll — CHANGES_REQUESTED** [review]
@Yashika27 
**Thank you so much for your contribution and do provide a detailed description of what type of contribution you've done and put your GitHub username either at the top or end of the code**

**Comment by Yashika27** [comment]
@hanshulll 
Thanks for the review. I've added the username and the problem description was already there. Please let me know if anything else is required.

**Comment by hanshulll** [comment]
> @hanshulll
> Thanks for the review. I've added the username and the problem description was already there. Please let me know if anything else is required.
@Yashika27 
**Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be helped but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**

**Comment by Yashika27** [comment]
@hanshulll 
Yeah just saw that. No worries, I'll try creating more PRs for the fest.
I ain't sure but accepting/rejecting the PRs more frequently might help in such cases.

**Pull request closed without merging**
