### PR TITLE
Create matrixinzigzag.cpp

### PR DESCRIPTION
**Pull request by varsha080**
I have written this code to print the matrix in zigzag format. Kindly review it ang merge it.

### CODE REVIEW

**Review by hanshulll — APPROVED** [review]
@varsha080 
**Your PR will be merged soon in the meantime give a star to the repo if it helps 🙌🏻**

**Comment by varsha080** [comment]
Thank you for merging and surely I'll

**Comment by varsha080** [comment]
@hanshulll when my PR will be merged?

**Comment by hanshulll** [comment]
@varsha080 
**Actually see their are too many PR’s right now and if I blindly just merge them then this repo is going to get excluded from the hactoberfest so be patient full we have a whole month and even if it has hacktoberfest-accepted tag it’s still good to go. So keep hackin**

**Pull request merged**
