### PR TITLE
Create InputDisplay and PrimeNumberAdder in Kotlin

### PR DESCRIPTION
**Pull request by mayorJAY**

### CODE REVIEW

**Review by hanshulll — CHANGES_REQUESTED** [review]
@mayorJAY 
**Thank you so much for your contribution and do provide a detailed description of what type of contribution you've done and put your GitHub username either at the top or end of the code**

**Comment by mayorJAY** [comment]
@hanshulll I have done as requested. Also, kindly remember to add the Hacktoberfest-accepted label on this PR

**Comment by hanshulll** [comment]
@mayorJAY 
**unfortunately this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be helped but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**

**Review by hanshulll — APPROVED** [review]
👍🏻

**Pull request merged**
